---
name: Build Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version:
          - "18"
          - "20"
          - "lts/*"
          - "latest"
    steps:
      - uses: actions/checkout@v4

      - name: Get PNPM version from package.json
        id: pnpm-version
        shell: bash
        run: echo "pnpm_version=$(node -p "require('./package.json').engines.pnpm")" >> "$GITHUB_OUTPUT"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ steps.pnpm-version.outputs.pnpm_version }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build documentation
        run: pnpm run docs:build
